services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17-alpine3.20
    ports:
      - "5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
  example:
    image: python:3.12.3-alpine3.18
    volumes:
      - ./example:/app
    ports:
      - "8080:80"
    command: ["python", "-m", "http.server", "80", "--directory", "/app"]
    restart: always