services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    ports:
      - "8080"
    volumes:
      - ./app:/app
    restart: always
    depends_on:
      db:
        condition: service_healthy
  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    volumes:
      - ./worker:/app
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17-alpine3.20
    ports:
      - "5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
